/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : ADCH.c
**     Project     : HCU_V0.2
**     Processor   : MC9S08DZ60MLH
**     Component   : ADC
**     Version     : Component 01.690, Driver 01.30, CPU db: 3.00.026
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2017-05-18, 19:05, # CodeGen: 11
**     Abstract    :
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
**     Settings    :
**          Component name                                 : ADCH
**          A/D converter                                  : ADC
**          Sharing                                        : Disabled
**          Interrupt service/event                        : Enabled
**            A/D interrupt                                : Vadc
**            A/D interrupt priority                       : low priority
**          A/D channels                                   : 13
**            Channel0                                     : 
**              A/D channel (pin)                          : PTA0_PIA0_ADP0_MCLK
**              A/D channel (pin) signal                   : 
**            Channel1                                     : 
**              A/D channel (pin)                          : PTA1_PIA1_ADP1_ACMP1PLUS
**              A/D channel (pin) signal                   : 
**            Channel2                                     : 
**              A/D channel (pin)                          : PTA2_PIA2_ADP2_ACMP1MINUS
**              A/D channel (pin) signal                   : 
**            Channel3                                     : 
**              A/D channel (pin)                          : PTA3_PIA3_ADP3_ACMP1O
**              A/D channel (pin) signal                   : 
**            Channel4                                     : 
**              A/D channel (pin)                          : PTA4_PIA4_ADP4
**              A/D channel (pin) signal                   : 
**            Channel5                                     : 
**              A/D channel (pin)                          : PTA5_PIA5_ADP5
**              A/D channel (pin) signal                   : 
**            Channel6                                     : 
**              A/D channel (pin)                          : PTA6_PIA6_ADP6
**              A/D channel (pin) signal                   : 
**            Channel7                                     : 
**              A/D channel (pin)                          : PTA7_PIA7_ADP7_IRQ
**              A/D channel (pin) signal                   : 
**            Channel8                                     : 
**              A/D channel (pin)                          : PTB0_PIB0_ADP8
**              A/D channel (pin) signal                   : 
**            Channel9                                     : 
**              A/D channel (pin)                          : PTB1_PIB1_ADP9
**              A/D channel (pin) signal                   : 
**            Channel10                                    : 
**              A/D channel (pin)                          : PTB2_PIB2_ADP10
**              A/D channel (pin) signal                   : 
**            Channel11                                    : 
**              A/D channel (pin)                          : PTB3_PIB3_ADP11
**              A/D channel (pin) signal                   : 
**            Channel12                                    : 
**              A/D channel (pin)                          : PTB4_PIB4_ADP12
**              A/D channel (pin) signal                   : 
**          A/D resolution                                 : 12 bits
**          Conversion time                                : 23 ?s
**          Low-power mode                                 : Disabled
**          Sample time                                    : long
**          External trigger                               : Disabled
**          Internal trigger                               : Disabled
**          Number of conversions                          : 8
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Events enabled in init.                      : yes
**          CPU clock/speed selection                      : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**          High input limit                               : 1
**          Low input limit                                : 0
**          Get value directly                             : yes
**          Wait for result                                : yes
**     Contents    :
**         Enable   - byte ADCH_Enable(void);
**         Disable  - byte ADCH_Disable(void);
**         Start    - byte ADCH_Start(void);
**         Stop     - byte ADCH_Stop(void);
**         Measure  - byte ADCH_Measure(bool WaitForResult);
**         GetValue - byte ADCH_GetValue(void* Values);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file ADCH.c
** @version 01.30
** @brief
**         This device "ADC" implements an A/D converter,
**         its control methods and interrupt/event handling procedure.
*/         
/*!
**  @addtogroup ADCH_module ADCH module documentation
**  @{
*/         


/* MODULE ADCH. */

#include "Events.h"
#include "ADCH.h"



static void ClrSumV(void);
/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define STOP            0x00U          /* STOP state           */
#define MEASURE         0x01U          /* MESURE state         */
#define CONTINUOUS      0x02U          /* CONTINUOS state      */
#define SINGLE          0x03U          /* SINGLE state         */


static const  byte Channels[13] = {0x40U,0x41U,0x42U,0x43U,0x44U,0x45U,0x46U,0x47U,0x48U,0x49U,0x4AU,0x4BU,0x4CU
};  /* Contents for the device control register */

static bool EnUser;                    /* Enable/Disable device */
static volatile bool OutFlg;           /* Measurement finish flag */
static volatile byte SumChan;          /* Number of measured channels */
static volatile byte ModeFlg;          /* Current state of device */
static volatile byte SumCnt;           /* Number of measured channels */

volatile word ADCH_SumV[13];           /* Temporary sum of measured values */
volatile word ADCH_OutV[13];           /* Sum of measured values */





/*
** ===================================================================
**     Method      :  ADCH_Interrupt (component ADC)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(ADCH_Interrupt)
{
  TWREG tmpTwreg;

  if (ModeFlg == STOP) {               /* If the driver is in STOP mode */
    (void)ADCRL;                       /* Clear interrupt flag */
    return;                            /* Return from interrupt */
  }
  /*lint -save  -e740 -e931 Disable MISRA rule (1.2) checking. */
  tmpTwreg.b.high = ADCRH;
  tmpTwreg.b.low = ADCRL;
  ADCH_SumV[SumChan] += tmpTwreg.w;    /* Save measured value */
  /*lint -restore Enable MISRA rule (1.2) checking. */
  SumChan++;                           /* Number of measurement */
  if (SumChan == 13U) {                /* Is number of measurement equal to the number of conversions? */
    SumChan = 0U;                      /* If yes then set the number of measurement to 0 */
    SumCnt++;
    if (SumCnt == 8U) {
      OutFlg = TRUE;                   /* Measured values are available */
      ADCH_OutV[0] = ADCH_SumV[0];     /* Save measured value to the output buffer */
      ADCH_OutV[1] = ADCH_SumV[1];     /* Save measured value to the output buffer */
      ADCH_OutV[2] = ADCH_SumV[2];     /* Save measured value to the output buffer */
      ADCH_OutV[3] = ADCH_SumV[3];     /* Save measured value to the output buffer */
      ADCH_OutV[4] = ADCH_SumV[4];     /* Save measured value to the output buffer */
      ADCH_OutV[5] = ADCH_SumV[5];     /* Save measured value to the output buffer */
      ADCH_OutV[6] = ADCH_SumV[6];     /* Save measured value to the output buffer */
      ADCH_OutV[7] = ADCH_SumV[7];     /* Save measured value to the output buffer */
      ADCH_OutV[8] = ADCH_SumV[8];     /* Save measured value to the output buffer */
      ADCH_OutV[9] = ADCH_SumV[9];     /* Save measured value to the output buffer */
      ADCH_OutV[10] = ADCH_SumV[10];   /* Save measured value to the output buffer */
      ADCH_OutV[11] = ADCH_SumV[11];   /* Save measured value to the output buffer */
      ADCH_OutV[12] = ADCH_SumV[12];   /* Save measured value to the output buffer */
      if (ModeFlg != MEASURE) {        /* Is the device in measure state? */
        ADCH_SumV[0] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[1] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[2] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[3] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[4] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[5] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[6] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[7] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[8] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[9] = 0U;             /* Set mesured values to 0 */
        ADCH_SumV[10] = 0U;            /* Set mesured values to 0 */
        ADCH_SumV[11] = 0U;            /* Set mesured values to 0 */
        ADCH_SumV[12] = 0U;            /* Set mesured values to 0 */
        SumCnt = 0U;                   /* Set number of conversions to 0 */
      }
      ADCH_OnEnd();                    /* Invoke user event */
      if (ModeFlg == MEASURE) {        /* Is the device in the measure state? */
        ModeFlg = STOP;                /* Set the device to the stop mode */
        return;                        /* Return from interrupt */
      }
    }
  }
  ADCSC1 = Channels[SumChan];          /* Start measurement of next channel */
}

/*
** ===================================================================
**     Method      :  ClrSumV (component ADC)
**
**     Description :
**         The method clears the internal buffers used to store sum of a 
**         number of last conversions.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void ClrSumV(void)
{
  ADCH_SumV[0] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[1] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[2] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[3] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[4] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[5] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[6] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[7] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[8] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[9] = 0U;                   /* Set variable for storing measured values to 0 */
  ADCH_SumV[10] = 0U;                  /* Set variable for storing measured values to 0 */
  ADCH_SumV[11] = 0U;                  /* Set variable for storing measured values to 0 */
  ADCH_SumV[12] = 0U;                  /* Set variable for storing measured values to 0 */
}

/*
** ===================================================================
**     Method      :  ADCH_HWEnDi (component ADC)
**
**     Description :
**         Enables or disables the peripheral(s) associated with the 
**         component. The method is called automatically as a part of the 
**         Enable and Disable methods and several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADCH_HWEnDi(void)
{
  if (EnUser) {                        /* Enable device? */
    if (ModeFlg) {                     /* Start or stop measurement? */
      SumCnt = 0U;                     /* Set the number of conversions */
      OutFlg = FALSE;                  /* Output values aren't available */
      SumChan = 0U;                    /* Set the number of measured channels to 0 */
      ClrSumV();                       /* Clear measured values */
      ADCSC1 = Channels[SumChan];      /* If yes then start the conversion */
    }
  }
  else {
    ADCSC1 = 0x1FU;                    /* Disable the device */
  }
}

/*
** ===================================================================
**     Method      :  ADCH_Enable (component ADC)
*/
/*!
**     @brief
**         Enables A/D converter component. [Events] may be generated
**         ([DisableEvent]/[EnableEvent]). If possible, this method
**         switches on A/D converter device, voltage reference, etc.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte ADCH_Enable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    return ERR_OK;                     /* If yes then set the flag "device enabled" */
  }
  EnUser = TRUE;                       /* Set the flag "device enabled" */
  ADCH_HWEnDi();                       /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_Disable (component ADC)
*/
/*!
**     @brief
**         Disables A/D converter component. No [events] will be
**         generated. If possible, this method switches off A/D
**         converter device, voltage reference, etc.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte ADCH_Disable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_OK;                     /* If yes then OK */
  }
  EnUser = FALSE;                      /* If yes then set the flag "device disabled" */
  ADCH_HWEnDi();                       /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_Start (component ADC)
*/
/*!
**     @brief
**         This method starts continuous conversion on all channels
**         that are set in the component inspector. When each
**         measurement on all channels has finished the [OnEnd ] event
**         may be invoked. This method is not available if the
**         [interrupt service] is disabled and the device doesn't
**         support the continuous mode. Note: If time of measurement is
**         too short and the instruction clock is too slow then the
**         conversion complete interrupt and its handler may cause a
**         system overflow.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
byte ADCH_Start(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in running mode? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = CONTINUOUS;                /* Set state of device to the continuos mode */
  ADCH_HWEnDi();                       /* Enable the device */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_Stop (component ADC)
**     Description :
**         This method stops the continuous measurement or disables
**         a trigger mode (if supported by HW), which has been
**         started by one of the following methods:
**         Version specific information for Freescale HCS08 and HC08
**         derivatives ] 
**         - <Start> 
**         - <EnableIntChanTrigger>
**         - <EnableExtChanTrigger>
**         The Stop method is available if one of the previously
**         mentioned methods is supported by A/D converter device
**         and is enabled to be generated.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_BUSY - No continuous measurement is
**                           running. Neither internal trigger nor
**                           external trigger have been enabled (if
**                           these are supported by HW).
** ===================================================================
*/
byte ADCH_Stop(void)
{
  if (ModeFlg != CONTINUOUS) {         /* Is the device in different mode than "continuous"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = STOP;                      /* Set state of device to the stop mode */
  ADCSC1 = 0x1FU;                      /* Abort the current conversion */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_Measure (component ADC)
*/
/*!
**     @brief
**         This method performs one measurement on all channels that
**         are set in the component inspector. (Note: If the [number of
**         conversions] is more than one the conversion of A/D channels
**         is performed specified number of times.)
**     @param
**         WaitForResult   - Wait for a result of a
**                           conversion. If [interrupt service] is
**                           disabled, A/D peripheral doesn't support
**                           measuring all channels at once or Autoscan
**                           mode property isn't enabled and at the same
**                           time the [number of channels] is greater
**                           than 1, then the WaitForResult parameter is
**                           ignored and the method waits for each
**                           result every time. If the [interrupt
**                           service] is disabled and a [number of
**                           conversions] is greater than 1, the
**                           parameter is ignored and the method also
**                           waits for each result every time.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled
**                           ERR_BUSY - A conversion is already running
*/
/* ===================================================================*/
#pragma MESSAGE DISABLE C5703 /* WARNING C5703: Parameter declared but not referenced */
byte ADCH_Measure(bool WaitForResult)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    return ERR_DISABLED;               /* If yes then error */
  }
  if (ModeFlg != STOP) {               /* Is the device in different mode than "stop"? */
    return ERR_BUSY;                   /* If yes then error */
  }
  ModeFlg = MEASURE;                   /* Set state of device to the measure mode */
  ADCH_HWEnDi();                       /* Enable the device */
  if (WaitForResult) {                 /* Is WaitForResult TRUE? */
    while (ModeFlg == MEASURE) {}      /* If yes then wait for end of measurement */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_GetValue (component ADC)
*/
/*!
**     @brief
**         Returns the last measured values for all channels. Format
**         and width of the value is a native format of the A/D
**         converter.
**     @param
**         Values          - Pointer to the array that contains
**                           the measured data. Data type is a byte, a
**                           word or an int. It depends on the supported
**                           modes, resolution, etc. of the AD converter.
**                           See the Version specific information for
**                           the current CPU in [General Info].
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_NOTAVAIL - Requested value not
**                           available
**                           ERR_OVERRUN - External trigger overrun flag
**                           was detected after the last value(s) was
**                           obtained (for example by GetValue). This
**                           error may not be supported on some CPUs
**                           (see generated code).
*/
/* ===================================================================*/
byte ADCH_GetValue(void *Values)
{
  if (OutFlg == 0U) {                  /* Is output flag set? */
    return ERR_NOTAVAIL;               /* If no then error */
  }
  ((word*)Values)[0] = (word)(ADCH_OutV[0] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[1] = (word)(ADCH_OutV[1] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[2] = (word)(ADCH_OutV[2] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[3] = (word)(ADCH_OutV[3] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[4] = (word)(ADCH_OutV[4] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[5] = (word)(ADCH_OutV[5] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[6] = (word)(ADCH_OutV[6] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[7] = (word)(ADCH_OutV[7] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[8] = (word)(ADCH_OutV[8] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[9] = (word)(ADCH_OutV[9] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[10] = (word)(ADCH_OutV[10] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[11] = (word)(ADCH_OutV[11] / 8U); /* Save measured values to the output buffer */
  ((word*)Values)[12] = (word)(ADCH_OutV[12] / 8U); /* Save measured values to the output buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  ADCH_Init (component ADC)
**
**     Description :
**         Initializes the associated peripheral(s) and the component's 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void ADCH_Init(void)
{
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=1,ADCH3=1,ADCH2=1,ADCH1=1,ADCH0=1 */
  setReg8(ADCSC1, 0x1FU);              /* Disable the module */ 
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0,??=0,??=0,??=0,??=0 */
  setReg8(ADCSC2, 0x00U);              /* Disable HW trigger and autocompare */ 
  EnUser = TRUE;                       /* Enable device */
  OutFlg = FALSE;                      /* No measured value */
  ModeFlg = STOP;                      /* Device isn't running */
  /* ADCCFG: ADLPC=0,ADIV1=1,ADIV0=1,ADLSMP=1,MODE1=0,MODE0=1,ADICLK1=0,ADICLK0=1 */
  setReg8(ADCCFG, 0x75U);              /* Set prescaler bits */ 
  ADCH_HWEnDi();                       /* Enable/disable device according to the status flags */
}


/* END ADCH. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
